version: '3'

services:
  db:
    image: mysql:5.7
    container_name: vizards_mysqldb
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'vizards'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'hello'
       MYSQL_ROOT_PASSWORD: 'hello'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: vizards_django
    volumes:
      - .:/vizards_docker_image
    ports:
      - "8000:8000"
    depends_on:
      - db